[package]
name = "rana"
version = "0.2.1"
edition = "2021"
license = "MIT"
authors = ["Francisco Calder√≥n <fjcalderon@gmail.com>"]
description = "Nostr public key mining tool"

[dependencies]
bech32 = "*"
bitcoin_hashes = "0.11.0"
hex = "*"
regex = "1"
secp256k1 = { version = "0.24.1", features = ["rand-std"] }
num_cpus = "1.1"

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 3
